---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  data_bags_path: /tmp/databags
  # encrypted_data_bag_secret_key_path: /tmp/kitchen/data_bags
  log_file: /tmp/chef_zero.log
  #log_level: debug
# Comment here
  #root_path: /tmp

verifier:
  name: inspec
  log_level: debug

platforms:
  - name: ubuntu-16.04
#  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[encrypted-databag::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
